version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1
  lumos: hevodata/lumos@dev:alpha

parameters:
  target_branch:
    description: Regex for target branch (main branches)
    type: string
    default: "^(dev)|^(release*)"
  release_build_trigger:
    description: Flag for release build pipeline.trigger_source
    type: boolean
    default: false
  skip_tests:
    description: Flag to manage skipping of test execution
    type: boolean
    default: false
  hotfix_branch_cut:
    description: Flag to manage if hotfix branch cut
    type: boolean
    default: false
  debug_release_branch_cut:
    description: Flag to manage if debug release branch cut
    type: boolean
    default: false
  release_branch_cut:
    description: Flag to manage if release branch cut
    type: boolean
    default: false
  build_tool:
    type: string
    default: maven #change this value as per requirement

jobs:
  generate_dynamic_configuration:
    executor: lumos/deploy-executor
    steps:
      - checkout
      - lumos/build_services_command:
          build_type: "library"
      - continuation/continue:
          configuration_path: .circleci/generated-config.yml
          parameters: '{
              "build_tool":"<<pipeline.parameters.build_tool>>"
            }'

workflows:
  Generate Config:
    jobs:
      - generate_dynamic_configuration:
          name: Generate CI configuration
